load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "logger",
    srcs = [
        "logger.cpp",
    ],
    hdrs = [
        "logger.hpp",
    ],
    visibility = ["//visibility:public"],
)
