load("@rules_cc//cc:defs.bzl", "cc_library")

package(
    default_testonly = True,
    default_visibility = ["//src/parsers/combinator:__subpackages__"],
)

cc_library(
    name = "utils",
    hdrs = [
        "utils.hpp",
    ],
)
