load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_library(
  name = "testing",
  hdrs = [
    "widget.hpp",
  ],
  visibility = ["//src/streams:__subpackages__"],
)
