load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "view",
    hdrs = [
        "ptr_iterator.hpp",
        "view.hpp",
    ],
    visibility = ["//src/streams:__subpackages__"],
)

cc_library(
    name = "ptr_iterator",
    hdrs = [
        "ptr_iterator.hpp",
    ],
    visibility = ["//src/streams:__subpackages__"],
)
