load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//src/parsers/combinator:__subpackages__"])

cc_library(
    name = "parsers",
    hdrs = [
        "num_parser.hpp",
        "parser.hpp",
        "parsers.hpp",
        "sequence_parser.hpp",
        "string_parser.hpp",
    ],
)
