load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "test_map",
    size = "small",
    srcs = ["test_map.cpp"],
    deps = [
        "//src/streams:stream",
        "//src/testing:unit_test",
        "//src/testing:widget",
    ],
)

cc_test(
    name = "test_filter",
    size = "small",
    srcs = ["test_filter.cpp"],
    deps = [
        "//src/streams:stream",
        "//src/testing:unit_test",
        "//src/testing:widget",
    ],
)

cc_test(
    name = "test_distinct",
    size = "small",
    srcs = ["test_distinct.cpp"],
    deps = [
        "//src/streams:stream",
        "//src/testing:unit_test",
        "//src/testing:widget",
    ],
)

cc_test(
    name = "test_reduce",
    size = "small",
    srcs = ["test_reduce.cpp"],
    deps = [
        "//src/streams:stream",
        "//src/testing:unit_test",
        "//src/testing:widget",
    ],
)

cc_test(
    name = "test_sum",
    size = "small",
    srcs = ["test_sum.cpp"],
    deps = [
        "//src/streams:stream",
        "//src/testing:unit_test",
        "//src/testing:widget",
    ],
)

cc_test(
    name = "test_max",
    size = "small",
    srcs = ["test_max.cpp"],
    deps = [
        "//src/streams:stream",
        "//src/testing:unit_test",
        "//src/testing:widget",
    ],
)

cc_test(
    name = "test_min",
    size = "small",
    srcs = ["test_min.cpp"],
    deps = [
        "//src/streams:stream",
        "//src/testing:unit_test",
        "//src/testing:widget",
    ],
)

cc_test(
    name = "test_for_each",
    size = "small",
    srcs = ["test_for_each.cpp"],
    deps = [
        "//src/streams:stream",
        "//src/testing:unit_test",
        "//src/testing:widget",
    ],
)
