load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "ostreamable",
    hdrs = [
        "ostreamable.hpp",
    ],
    visibility = ["//visibility:public"],
    deps = [":typing"],
)

cc_library(
    name = "timeit",
    hdrs = [
        "timeit.hpp",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "movable_fn",
    hdrs = [
        "movable_fn.hpp",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "typing",
    hdrs = [
        "more_type_traits.hpp",
    ],
    visibility = ["//visibility:public"],
)
