load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "print_stuff",
    hdrs = [
        "print_stuff.hpp",
    ],
    visibility = ["//visibility:public"],
    deps = [":typing"],
)

cc_library(
    name = "timeit",
    hdrs = [
        "timeit.hpp",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "movable_fn",
    hdrs = [
        "movable_fn.hpp",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "typing",
    hdrs = [
        "typing.hpp",
    ],
    visibility = ["//visibility:public"],
)
